using System;
namespace Wrox.DirectoryServices.Securiy
{
	[Flags]
	public enum ADS_RIGHTS_ENUM : uint
	{
		ADS_RIGHT_DELETE = 0x10000, 
		ADS_RIGHT_READ_CONTROL = 0x20000, 
		ADS_RIGHT_WRITE_DAC = 0x40000, 
		ADS_RIGHT_WRITE_OWNER = 0x80000, 
		ADS_RIGHT_SYNCHRONIZE = 0x100000, 
		ADS_RIGHT_ACCESS_SYSTEM_SECURITY = 0x1000000, 
		ADS_RIGHT_GENERIC_READ = 0x80000000, 
		ADS_RIGHT_GENERIC_WRITE = 0x40000000, 
		ADS_RIGHT_GENERIC_EXECUTE = 0x20000000, 
		ADS_RIGHT_GENERIC_ALL = 0x10000000, 
		ADS_RIGHT_DS_CREATE_CHILD = 0x1, 
		ADS_RIGHT_DS_DELETE_CHILD = 0x2, 
		ADS_RIGHT_ACTRL_DS_LIST = 0x4, 
		ADS_RIGHT_DS_SELF = 0x8, 
		ADS_RIGHT_DS_READ_PROP = 0x10, 
		ADS_RIGHT_DS_WRITE_PROP = 0x20, 
		ADS_RIGHT_DS_DELETE_TREE = 0x40, 
		ADS_RIGHT_DS_LIST_OBJECT = 0x80, 
		ADS_RIGHT_DS_CONTROL_ACCESS = 0x100
	}

	[Flags]
	public enum ADS_ACEFLAG_ENUM : byte
	{
		ADS_ACEFLAG_INHERIT_ACE = 0x2, 
		ADS_ACEFLAG_NO_PROPAGATE_INHERIT_ACE = 0x4, 
		ADS_ACEFLAG_INHERIT_ONLY_ACE = 0x8, 
		ADS_ACEFLAG_INHERITED_ACE = 0x10, 
		ADS_ACEFLAG_VALID_INHERIT_FLAGS = 0x1f, 
		ADS_ACEFLAG_SUCCESSFUL_ACCESS = 0x40, 
		ADS_ACEFLAG_FAILED_ACCESS = 0x80
	}

		
	[Flags]
	public enum ADS_ACETYPE_ENUM
	{
		ADS_ACETYPE_ACCESS_ALLOWED = 0, 
		ADS_ACETYPE_ACCESS_DENIED = 0x1, 
		ADS_ACETYPE_SYSTEM_AUDIT = 0x2, 
		ADS_ACETYPE_ACCESS_ALLOWED_OBJECT = 0x5, 
		ADS_ACETYPE_ACCESS_DENIED_OBJECT = 0x6, 
		ADS_ACETYPE_SYSTEM_AUDIT_OBJECT = 0x7, 
		ADS_ACETYPE_SYSTEM_ALARM_OBJECT = 0x8
	}

	[Flags]
	public enum ADS_FLAGTYPE_ENUM
	{
		ADS_FLAG_OBJECT_TYPE_PRESENT = 0x1, 
		ADS_FLAG_INHERITED_OBJECT_TYPE_PRESENT = 0x2
	}


	
}
